# Copyright 2025 Google LLC All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


steps:
  - name: gcr.io/cloud-builders/gsutil
    allowFailure: true
    args: ['cp', 'gs://ai-on-gke-website-htmltest-cache/.lycheecache', '.lycheecache']
  - name: 'ghcr.io/hugomods/hugo:ci-0.145.0'
    env:
      - GOPATH=/workspace/go
      - GO111MODULE=on
    script: |
      npm i autoprefixer
      hugo build -e production
  - name: lycheeverse/lychee
    args:
      - site/public
      - -c
      - lychee.toml
  - name: gcr.io/cloud-builders/gsutil
    args: ['cp', '.lycheecache', 'gs://ai-on-gke-website-htmltest-cache/.lycheecache']

options:
  logging: CLOUD_LOGGING_ONLY
