runtime: python39

handlers:
  - url: /
    static_files: public/index.html
    upload: public/*
    require_matching_file: true

  - url: /(.*)
    static_files: public/\1/index.html
    upload: public/*
    require_matching_file: true
  
  - url: /(.*)/
    static_files: public/\1/index.html
    upload: public/*
    require_matching_file: true

  - url: /
    static_dir: public/
    require_matching_file: true
